# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kohldampfmaschine
email: simonneutert@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Die Uhr steht auf Mahlzeit. Der Magen knurrt. Los wir gehen Edeka!
# baseurl: "/Kohldampfmaschine" # the subpath of your site, e.g. /blog
# url: "http://simonneutert.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  simonneutert
repository: "simonneutert/kohldampfmaschine"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

permalink: /:categories/:title/
breadcrumbs: true  # disabled by default

paginate: 4 # amount of posts to show
paginate_path: /page:num/

og_image: /assets/images/kohldampfmaschine-og.jpg

# Collections
# collections:
#   recipes:
#     output: true
#     permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

plugins:
  - jekyll-remote-theme
  - jekyll-data
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

locale: de
search: true
timezone: Europe/Berlin

google_site_verification: uOkZ5Hhj1TeI02Wt680PeDo0nlAfhKMjWADqsvnoeHM

footer:
  links:
    - label: "Simon Neutert"
      icon: "far fa-fw fa-address-card"
      url: "https://www.simon-neutert.de"
    - label: "WTFPL Lizenz"
      icon: "fas fa-fw fa-gavel"
      url: "http://www.wtfpl.net/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
